# NEOMAK employes can change the features and use the model to predict real estate values. [Model designed by: Mohammed Asim Furqaan]

In [1]:
from joblib import dump,load
model = load('NEOMAK.joblib')

In [2]:
import numpy as np

In [3]:
features1 = (np.array([[-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
        -0.2438205 , -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
        -0.97491834,  0.41164221, -0.86091034]]))
model.predict(features1)

array([22.291])

In [4]:
features2 =  (np.array([[-0.44352175,  3.12628155, -1.35893781, -0.27288841, -1.0542567 ,
         0.49725126, -1.3938808 ,  2.19312325, -0.65766683, -0.78557904,
        -0.69277865,  0.39131918, -0.94116739]]))
model.predict(features2)

array([25.53])

In [5]:
features4 =  (np.array([[-0.40786253, -0.4898311 , -0.57719868, -0.27288841, -0.5573845 ,
        0.04304598, -1.42222622,  0.79643404, -0.5429938 , -0.74402708,
        0.52982668,  0.45343469, -0.91902752]]))
model.predict(features4)

array([23.689])